#pragma once

#include "Opcode.h"

//All opcode handlers
#include "opcodes/prefix.h"
#include "opcodes/cp.h"
#include "opcodes/incdec.h"
#include "opcodes/io.h"
#include "opcodes/jp.h"
#include "opcodes/ld.h"
#include "opcodes/nop.h"

namespace emu
{
	namespace cpu
	{
		namespace z80
		{
			static const Opcode OpcodeTable[] =
			{
				{ 0x00, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x01, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x02, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x03, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x04, 0, &opcodes::INC_B,   "INC B" },
				{ 0x05, 0, &opcodes::DEC_B,   "DEC B" },
				{ 0x06, 1, &opcodes::LD_B,    "LD B" },
				{ 0x07, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x08, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x09, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x0A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x0B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x0C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x0D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x0E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x0F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x10, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x11, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x12, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x13, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x14, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x15, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x16, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x17, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x18, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x19, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x1A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x1B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x1C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x1D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x1E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x1F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x20, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x21, 2, &opcodes::LD_HL,   "LD HL" },
				{ 0x22, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x23, 0, &opcodes::INC_HL,  "INC HL" },
				{ 0x24, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x25, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x26, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x27, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x28, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x29, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x2A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x2B, 0, &opcodes::DEC_HL,  "DEC_HL" },
				{ 0x2C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x2D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x2E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x2F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x30, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x31, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x32, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x33, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x34, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x35, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x36, 1, &opcodes::LD_ADDR_HL, "LD (HL),#" },
				{ 0x37, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x38, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x39, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x3A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x3B, 0, &opcodes::INC_A,   "INC A" },
				{ 0x3C, 0, &opcodes::DEC_A,   "DEC A" },
				{ 0x3D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x3E, 1, &opcodes::LD_A,    "LD A" },
				{ 0x3F, 1, &opcodes::Unknown, "UNKNOWN" },
				
				{ 0x40, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x41, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x42, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x43, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x44, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x45, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x46, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x47, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x48, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x49, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x4A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x4B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x4C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x4D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x4E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x4F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x50, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x51, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x52, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x53, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x54, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x55, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x56, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x57, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x58, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x59, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x5A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x5B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x5C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x5D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x5E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x5F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x60, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x61, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x62, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x63, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x64, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x65, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x66, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x67, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x68, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x69, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x6A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x6B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x6C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x6D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x6E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x6F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x70, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x71, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x72, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x73, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x74, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x75, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x76, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x77, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x78, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x79, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x7A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x7B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x7C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x7D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x7E, 0, &opcodes::LD_A_HL, "LD A,(HL)" },
				{ 0x7F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x80, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x81, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x82, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x83, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x84, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x85, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x86, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x87, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x88, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x89, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x8A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x8B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x8C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x8D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x8E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x8F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0x90, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x91, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x92, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x93, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x94, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x95, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x96, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x97, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x98, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x99, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x9A, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x9B, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x9C, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x9D, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x9E, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0x9F, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0xA0, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA1, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA2, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA3, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA4, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA5, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA6, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA7, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA8, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xA9, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xAA, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xAB, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xAC, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xAD, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xAE, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xAF, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0xB0, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB1, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB2, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB3, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB4, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB5, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB6, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB7, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xB8, 0, &opcodes::CP_B,    "CP_B" },
				{ 0xB9, 0, &opcodes::CP_C,    "CP_C" },
				{ 0xBA, 0, &opcodes::CP_D,    "CP_D" },
				{ 0xBB, 0, &opcodes::CP_E,    "CP_E" },
				{ 0xBC, 0, &opcodes::CP_H,    "CP_H" },
				{ 0xBD, 0, &opcodes::CP_L,    "CP_L" },
				{ 0xBE, 0, &opcodes::CP_HL,   "CP_HL" },
				{ 0xBF, 0, &opcodes::CP_A,    "CP_A" },

				{ 0xC0, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC1, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC2, 2, &opcodes::JP_NZ,   "JP_NZ" },
				{ 0xC3, 2, &opcodes::JP,      "JP" },
				{ 0xC4, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC5, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC6, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC7, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC8, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xC9, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xCA, 2, &opcodes::JP_Z,    "JP Z" },
				{ 0xCB, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xCC, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xCD, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xCE, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xCF, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0xD0, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD1, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD2, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD3, 1, &opcodes::OUT_A,   "OUT #,A" },
				{ 0xD4, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD5, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD6, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD7, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD8, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xD9, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xDA, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xDB, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xDC, 1, &opcodes::Unknown, "UNKNOWN" },

				//Redirects for prefixes
				{ 0xDD, 1, &opcodes::Prefix_DD, "" },
				{ 0xDE, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xDF, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0xE0, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE1, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE2, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE3, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE4, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE5, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE6, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE7, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE8, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xE9, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xEA, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xEB, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xEC, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xED, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xEE, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xEF, 1, &opcodes::Unknown, "UNKNOWN" },

				{ 0xF0, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF1, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF2, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF3, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF4, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF5, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF6, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF7, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF8, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xF9, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xFA, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xFB, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xFC, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xFD, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xFE, 1, &opcodes::Unknown, "UNKNOWN" },
				{ 0xFF, 1, &opcodes::Unknown, "UNKNOWN" },
			};
		}
	}
}