#pragma once

#include "Opcode.h"

//All opcode handlers
#include "opcodes/prefix.h"
#include "opcodes/stack.h"
#include "opcodes/cp.h"
#include "opcodes/ex.h"
#include "opcodes/halt.h"
#include "opcodes/incdec.h"
#include "opcodes/interrupts.h"
#include "opcodes/io.h"
#include "opcodes/jp.h"
#include "opcodes/ld.h"
#include "opcodes/nop.h"
#include "opcodes/bitwise.h"

namespace emu
{
	namespace cpu
	{
		namespace z80
		{
			static const Opcode OpcodeTable[] =
			{
				{ 0x00, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x01, 2, &opcodes::LD_r16_n8,	"LD", "BF, ##" },
				{ 0x02, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x03, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x04, 0, &opcodes::INC_r8,	"INC", "B" },
				{ 0x05, 0, &opcodes::DEC_r8,	"DEC", "B" },
				{ 0x06, 1, &opcodes::LD_r8_n8,	"LD", "B, #" },
				{ 0x07, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x08, 0, &opcodes::EX_AF_AFa,	"EX", "AF, AF'" },
				{ 0x09, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x0A, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x0B, 0, &opcodes::DEC_r16,	"DEC", "BC" },
				{ 0x0C, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x0D, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x0E, 1, &opcodes::LD_r8_n8,	"LD", "C, #" },
				{ 0x0F, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0x10, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x11, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x12, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x13, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x14, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x15, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x16, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x17, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x18, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x19, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x1A, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x1B, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x1C, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x1D, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x1E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x1F, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0x20, 1, &opcodes::JR_NZ_n8,	"JR", "NZ, #" },
				{ 0x21, 2, &opcodes::LD_r16_n8,	"LD", "HL, ##" },
				{ 0x22, 2, &opcodes::LD_n16_HL,	"LD", "##, HL" },
				{ 0x23, 0, &opcodes::INC_r16,	"INC", "HL" },
				{ 0x24, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x25, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x26, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x27, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x28, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x29, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x2A, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x2B, 0, &opcodes::DEC_r16,	"DEC", "HL" },
				{ 0x2C, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x2D, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x2E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x2F, 0, &opcodes::CPL_A,		"CPL_A", "" },

				{ 0x30, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x31, 2, &opcodes::LD_r16_n8,	"LD", "SP, ##" },
				{ 0x32, 2, &opcodes::LD_n16_A,	"LD", "##, A" },
				{ 0x33, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x34, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x35, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x36, 1, &opcodes::LD_dHL_n8,	"LD", "(HL), #" },
				{ 0x37, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x38, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x39, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x3A, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x3B, 0, &opcodes::INC_r8,	"INC", "A" },
				{ 0x3C, 0, &opcodes::DEC_r8,	"DEC", "A" },
				{ 0x3D, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x3E, 1, &opcodes::LD_r8_n8,	"LD", "A, #" },
				{ 0x3F, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				
				{ 0x40, 0, &opcodes::LD_r8_r8,	"LD", "B, B" },
				{ 0x41, 0, &opcodes::LD_r8_r8,	"LD", "B, C" },
				{ 0x42, 0, &opcodes::LD_r8_r8,	"LD", "B, D" },
				{ 0x43, 0, &opcodes::LD_r8_r8,	"LD", "B, E" },
				{ 0x44, 0, &opcodes::LD_r8_r8,	"LD", "B, H" },
				{ 0x45, 0, &opcodes::LD_r8_r8,	"LD", "B, L" },
				{ 0x46, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x47, 0, &opcodes::LD_r8_r8,	"LD", "B, A" },
				{ 0x48, 0, &opcodes::LD_r8_r8,	"LD", "C, B" },
				{ 0x49, 0, &opcodes::LD_r8_r8,	"LD", "C, C" },
				{ 0x4A, 0, &opcodes::LD_r8_r8,	"LD", "C, D" },
				{ 0x4B, 0, &opcodes::LD_r8_r8,	"LD", "C, E" },
				{ 0x4C, 0, &opcodes::LD_r8_r8,	"LD", "C, H" },
				{ 0x4D, 0, &opcodes::LD_r8_r8,	"LD", "C, L" },
				{ 0x4E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x4F, 0, &opcodes::LD_r8_r8,	"LD", "C, A" },

				{ 0x50, 0, &opcodes::LD_r8_r8,	"LD", "D, B" },
				{ 0x51, 0, &opcodes::LD_r8_r8,	"LD", "D, C" },
				{ 0x52, 0, &opcodes::LD_r8_r8,	"LD", "D, D" },
				{ 0x53, 0, &opcodes::LD_r8_r8,	"LD", "D, E" },
				{ 0x54, 0, &opcodes::LD_r8_r8,	"LD", "D, H" },
				{ 0x55, 0, &opcodes::LD_r8_r8,	"LD", "D, L" },
				{ 0x56, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x57, 0, &opcodes::LD_r8_r8,	"LD", "D, A" },
				{ 0x58, 0, &opcodes::LD_r8_r8,	"LD", "E, B" },
				{ 0x59, 0, &opcodes::LD_r8_r8,	"LD", "E, C" },
				{ 0x5A, 0, &opcodes::LD_r8_r8,	"LD", "E, D" },
				{ 0x5B, 0, &opcodes::LD_r8_r8,	"LD", "E, E" },
				{ 0x5C, 0, &opcodes::LD_r8_r8,	"LD", "E, H" },
				{ 0x5D, 0, &opcodes::LD_r8_r8,	"LD", "E, L" },
				{ 0x5E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x5F, 0, &opcodes::LD_r8_r8,	"LD", "E, A" },

				{ 0x60, 0, &opcodes::LD_r8_r8,	"LD", "H, B" },
				{ 0x61, 0, &opcodes::LD_r8_r8,	"LD", "H, C" },
				{ 0x62, 0, &opcodes::LD_r8_r8,	"LD", "H, D" },
				{ 0x63, 0, &opcodes::LD_r8_r8,	"LD", "H, E" },
				{ 0x64, 0, &opcodes::LD_r8_r8,	"LD", "H, H" },
				{ 0x65, 0, &opcodes::LD_r8_r8,	"LD", "H, L" },
				{ 0x66, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x67, 0, &opcodes::LD_r8_r8,	"LD", "H, A" },
				{ 0x68, 0, &opcodes::LD_r8_r8,	"LD", "L, B" },
				{ 0x69, 0, &opcodes::LD_r8_r8,	"LD", "L, C" },
				{ 0x6A, 0, &opcodes::LD_r8_r8,	"LD", "L, D" },
				{ 0x6B, 0, &opcodes::LD_r8_r8,	"LD", "L, E" },
				{ 0x6C, 0, &opcodes::LD_r8_r8,	"LD", "L, H" },
				{ 0x6D, 0, &opcodes::LD_r8_r8,	"LD", "L, L" },
				{ 0x6E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x6F, 0, &opcodes::LD_r8_r8,	"LD", "L, A" },

				{ 0x70, 0, &opcodes::LD_dHL_r8,	 "LD", "(HL), B" },
				{ 0x71, 0, &opcodes::LD_dHL_r8,	 "LD", "(HL), C" },
				{ 0x72, 0, &opcodes::LD_dHL_r8,	 "LD", "(HL), D" },
				{ 0x73, 0, &opcodes::LD_dHL_r8,	 "LD", "(HL), E" },
				{ 0x74, 0, &opcodes::LD_dHL_r8,	 "LD", "(HL), H" },
				{ 0x75, 0, &opcodes::LD_dHL_r8,	 "LD", "(HL), L" },
				{ 0x76, 0, &opcodes::HALT,		"HALT", "" },
				{ 0x77, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x78, 0, &opcodes::LD_r8_r8,	"LD", "A, B" },
				{ 0x79, 0, &opcodes::LD_r8_r8,	"LD", "A, C" },
				{ 0x7A, 0, &opcodes::LD_r8_r8,	"LD", "A, D" },
				{ 0x7B, 0, &opcodes::LD_r8_r8,	"LD", "A, E" },
				{ 0x7C, 0, &opcodes::LD_r8_r8,	"LD", "A, H" },
				{ 0x7D, 0, &opcodes::LD_r8_r8,	"LD", "A, L" },
				{ 0x7E, 0, &opcodes::LD_r8_dHL,	"LD", "A, (HL)" },
				{ 0x7F, 0, &opcodes::LD_r8_r8,	"LD", "A, A" },

				{ 0x80, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x81, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x82, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x83, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x84, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x85, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x86, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x87, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x88, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x89, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x8A, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x8B, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x8C, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x8D, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x8E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x8F, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0x90, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x91, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x92, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x93, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x94, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x95, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x96, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x97, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x98, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x99, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x9A, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x9B, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x9C, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x9D, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x9E, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0x9F, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0xA0, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA1, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA2, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA3, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA4, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA5, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA6, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA7, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA8, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xA9, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xAA, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xAB, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xAC, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xAD, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xAE, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xAF, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0xB0, 0, &opcodes::OR_A_r8,	"OR", "B" },
				{ 0xB1, 0, &opcodes::OR_A_r8,	"OR", "C" },
				{ 0xB2, 0, &opcodes::OR_A_r8,	"OR", "D" },
				{ 0xB3, 0, &opcodes::OR_A_r8,	"OR", "E" },
				{ 0xB4, 0, &opcodes::OR_A_r8,	"OR", "H" },
				{ 0xB5, 0, &opcodes::OR_A_r8,	"OR", "L" },
				{ 0xB6, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xB7, 0, &opcodes::OR_A_r8,	"OR", "A" },
				{ 0xB8, 0, &opcodes::CP_A_r8,	"CP", "B" },
				{ 0xB9, 0, &opcodes::CP_A_r8,	"CP", "C" },
				{ 0xBA, 0, &opcodes::CP_A_r8,	"CP", "D" },
				{ 0xBB, 0, &opcodes::CP_A_r8,	"CP", "E" },
				{ 0xBC, 0, &opcodes::CP_A_r8,	"CP", "H" },
				{ 0xBD, 0, &opcodes::CP_A_r8,	"CP", "L" },
				{ 0xBE, 0, &opcodes::CP_A_dHL,	"CP", "HL" },
				{ 0xBF, 0, &opcodes::CP_A_r8,	"CP", "A" },

				{ 0xC0, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xC1, 0, &opcodes::POP_r16,	"POP", "BC" },
				{ 0xC2, 2, &opcodes::JP_NZ_n16,	"JP", "NZ, ##" },
				{ 0xC3, 2, &opcodes::JP_n16,	"JP", "##" },
				{ 0xC4, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xC5, 0, &opcodes::PUSH_r16,	"PUSH", "BC" },
				{ 0xC6, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xC7, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xC8, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xC9, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xCA, 2, &opcodes::JP_Z_n16,	"JP", "Z, ##" },
				{ 0xCB, 1, &opcodes::Prefix_CB,	"", "" },
				{ 0xCC, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xCD, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xCE, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xCF, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0xD0, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xD1, 0, &opcodes::POP_r16,	"POP", "DE" },
				{ 0xD2, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xD3, 1, &opcodes::OUT_A,		"OUT", "#, A" },
				{ 0xD4, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xD5, 0, &opcodes::PUSH_r16,	"PUSH", "DE" },
				{ 0xD6, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xD7, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xD8, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xD9, 0, &opcodes::EXX,		"EXX", "" },
				{ 0xDA, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xDB, 1, &opcodes::IN_A,		"IN", "A, #" },
				{ 0xDC, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xDD, 1, &opcodes::Prefix_DD,	"", "" },
				{ 0xDE, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xDF, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0xE0, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xE1, 0, &opcodes::POP_r16,	"POP", "HL" },
				{ 0xE2, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xE3, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xE4, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xE5, 0, &opcodes::PUSH_r16,	"PUSH", "HL" },
				{ 0xE6, 1, &opcodes::AND_A_n8,	"AND", "A, #" },
				{ 0xE7, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xE8, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xE9, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xEA, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xEB, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xEC, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xED, 1, &opcodes::Prefix_ED,	"", "" },
				{ 0xEE, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xEF, 0, &opcodes::Unknown,	"UNKNOWN", "" },

				{ 0xF0, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xF1, 0, &opcodes::POP_r16,	"POP", "AF" },
				{ 0xF2, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xF3, 0, &opcodes::DI,		"DI", "" },
				{ 0xF4, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xF5, 0, &opcodes::PUSH_r16,	"PUSH", "AF" },
				{ 0xF6, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xF7, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xF8, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xF9, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xFA, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xFB, 0, &opcodes::EI,		"EI", "" },
				{ 0xFC, 0, &opcodes::Unknown,	"UNKNOWN", "" },
				{ 0xFD, 1, &opcodes::Prefix_FD,	"", "" },
				{ 0xFE, 1, &opcodes::CP_A_n8,	"CP", "#" },
				{ 0xFF, 0, &opcodes::Unknown,	"UNKNOWN", "" },
			};
		}
	}
}